//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carbonfrost.Commons.Hxl.Compiler {
    using System.Linq;
    using System; /*;
    using System;
    
    
    public partial class ClassName : */ partial class CSTemplateGenerator : TemplateBase {
        
        public override string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 4 ""
            this.Write("\n#pragma warning disable CS8019\n\n// File automatically generated at ");
            
            #line default
            #line hidden
            
            #line 7 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( DateTime.Now ));
            
            #line default
            #line hidden
            
            #line 7 ""
            this.Write("\nnamespace ");
            
            #line default
            #line hidden
            
            #line 8 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( this.Namespace ));
            
            #line default
            #line hidden
            
            #line 8 ""
            this.Write(" {\n\nusing System;\nusing System.Linq;\nusing Carbonfrost.Commons.Hxl;\n");
            
            #line default
            #line hidden
            
            #line 13 ""
 foreach (var u in this.Usings) { 
            
            #line default
            #line hidden
            
            #line 14 ""
            this.Write("using ");
            
            #line default
            #line hidden
            
            #line 14 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( u ));
            
            #line default
            #line hidden
            
            #line 14 ""
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 15 ""
 } 
            
            #line default
            #line hidden
            
            #line 16 ""
            this.Write("\n    [global::System.CodeDom.Compiler.GeneratedCode(\"");
            
            #line default
            #line hidden
            
            #line 17 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( this.CodeGenerator ));
            
            #line default
            #line hidden
            
            #line 17 ""
            this.Write("\", \"");
            
            #line default
            #line hidden
            
            #line 17 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( this.CodeGeneratorVersion ));
            
            #line default
            #line hidden
            
            #line 17 ""
            this.Write("\")]\n    [global::Carbonfrost.Commons.Hxl.HxlTemplate(Name = \"");
            
            #line default
            #line hidden
            
            #line 18 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( this.TemplateName ));
            
            #line default
            #line hidden
            
            #line 18 ""
            this.Write("\")]\n    partial class ");
            
            #line default
            #line hidden
            
            #line 19 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( this.ClassName ));
            
            #line default
            #line hidden
            
            #line 19 ""
            this.Write("\n        : global::");
            
            #line default
            #line hidden
            
            #line 20 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( this.BaseClass ));
            
            #line default
            #line hidden
            
            #line 20 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 21 ""
 if (this.HasDocument) { 
            
            #line default
            #line hidden
            
            #line 22 ""
            this.Write("          , global::Carbonfrost.Commons.Hxl.IHxlDocumentAccessor\n");
            
            #line default
            #line hidden
            
            #line 23 ""
 } 
            
            #line default
            #line hidden
            
            #line 24 ""
            this.Write("    {\n\n");
            
            #line default
            #line hidden
            
            #line 26 ""
 if (this.HasDocument) { 
            
            #line default
            #line hidden
            
            #line 27 ""
            this.Write(@"        private global::Carbonfrost.Commons.Hxl.HxlDocument __document;

        global::Carbonfrost.Commons.Hxl.HxlDocument global::Carbonfrost.Commons.Hxl.IHxlDocumentAccessor.Document {
            get {
                if (!this.IsInitialized)
                    this.Initialize();

                return this.__document;
            }
        }
");
            
            #line default
            #line hidden
            
            #line 37 ""
 } 
            
            #line default
            #line hidden
            
            #line 38 ""
            this.Write("\n        private void InitializeComponent() {\n");
            
            #line default
            #line hidden
            
            #line 40 ""
 if (this.InitializeComponent.Length > 0) { 
            
            #line default
            #line hidden
            
            #line 41 ""
            this.Write("            var __self = this;\n");
            
            #line default
            #line hidden
            
            #line 42 ""
 } 
            
            #line default
            #line hidden
            
            #line 43 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 44 ""
 if (this.HasDocument) { 
            
            #line default
            #line hidden
            
            #line 45 ""
            this.Write("            this.__document = new global::Carbonfrost.Commons.Hxl.HxlDocument();\n" +
                    "");
            
            #line default
            #line hidden
            
            #line 46 ""
 } 
            
            #line default
            #line hidden
            
            #line 47 ""
            this.Write("\n        ");
            
            #line default
            #line hidden
            
            #line 48 ""
 foreach (var decl in this.DomNodeVariables) { 
            
            #line default
            #line hidden
            
            #line 49 ""
            this.Write("            global::Carbonfrost.Commons.Web.Dom.DomNode @");
            
            #line default
            #line hidden
            
            #line 49 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( decl ));
            
            #line default
            #line hidden
            
            #line 49 ""
            this.Write(";\n        ");
            
            #line default
            #line hidden
            
            #line 50 ""
 } 
            
            #line default
            #line hidden
            
            #line 51 ""
            this.Write("        ");
            
            #line default
            #line hidden
            
            #line 51 ""
 foreach (var decl in this.DomObjectVariables) { 
            
            #line default
            #line hidden
            
            #line 52 ""
            this.Write("            global::Carbonfrost.Commons.Web.Dom.DomObject @");
            
            #line default
            #line hidden
            
            #line 52 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( decl ));
            
            #line default
            #line hidden
            
            #line 52 ""
            this.Write(";\n        ");
            
            #line default
            #line hidden
            
            #line 53 ""
 } 
            
            #line default
            #line hidden
            
            #line 54 ""
            this.Write("\n            ");
            
            #line default
            #line hidden
            
            #line 55 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( this.InitializeComponent ));
            
            #line default
            #line hidden
            
            #line 55 ""
            this.Write("\n        }\n\n        ");
            
            #line default
            #line hidden
            
            #line 58 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( this.RenderIslands ));
            
            #line default
            #line hidden
            
            #line 58 ""
            this.Write("\n\n        protected override void TransformTextCore() {\n");
            
            #line default
            #line hidden
            
            #line 61 ""
 if (this.TransformTextCore.Length > 0) { 
            
            #line default
            #line hidden
            
            #line 62 ""
            this.Write("            var __self = this;\n");
            
            #line default
            #line hidden
            
            #line 63 ""
 } 
            
            #line default
            #line hidden
            
            #line 64 ""
 if (this.HasDocument) { 
            
            #line default
            #line hidden
            
            #line 65 ""
            this.Write("            this.__document.WriteTo(this.Output, this.TemplateContext);\n");
            
            #line default
            #line hidden
            
            #line 66 ""
 } else { 
            
            #line default
            #line hidden
            
            #line 67 ""
            this.Write("            dynamic __closure = this.TemplateContext;\n");
            
            #line default
            #line hidden
            
            #line 68 ""
 } 
            
            #line default
            #line hidden
            
            #line 69 ""
            this.Write("            ");
            
            #line default
            #line hidden
            
            #line 69 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( this.TransformTextCore ));
            
            #line default
            #line hidden
            
            #line 69 ""
            this.Write("\n        }\n\n        protected override void InitializeCore() {\n            base.I" +
                    "nitializeCore();\n            this.InitializeComponent();\n        }\n    }\n}\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public override void Initialize() {
            base.Initialize();
        }
    }
}
