//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carbonfrost.Commons.Hxl.Compiler {
    using System.Linq;
    using System; /*;
    using System;
    
    
    public partial class ClassName : */ partial class CSTemplateFactoryGenerator : TemplateBase {
        
        public override string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 4 ""
            this.Write("\n#pragma warning disable CS8019\n\nusing System;\nusing System.Linq;\nusing Carbonfro" +
                    "st.Commons.Hxl;\n\n[assembly: global::Carbonfrost.Commons.Hxl.HxlTemplateFactoryAt" +
                    "tribute(typeof(");
            
            #line default
            #line hidden
            
            #line 11 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( this.ClassName ));
            
            #line default
            #line hidden
            
            #line 11 ""
            this.Write("))]\n\nnamespace ");
            
            #line default
            #line hidden
            
            #line 13 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( this.Namespace ));
            
            #line default
            #line hidden
            
            #line 13 ""
            this.Write(" {\n\n    [global::System.CodeDom.Compiler.GeneratedCode(\"");
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( this.CodeGenerator ));
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write("\", \"");
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( this.CodeGeneratorVersion ));
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write("\")]\n    partial class ");
            
            #line default
            #line hidden
            
            #line 16 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( this.ClassName ));
            
            #line default
            #line hidden
            
            #line 16 ""
            this.Write(" : global::Carbonfrost.Commons.Hxl.HxlTemplateFactory {\n\n        public override " +
                    "HxlTemplate GetTemplate(string name) {\n            switch (name) {\n");
            
            #line default
            #line hidden
            
            #line 20 ""
 foreach (var templ in this.Templates) { 
            
            #line default
            #line hidden
            
            #line 21 ""
            this.Write("                case \"");
            
            #line default
            #line hidden
            
            #line 21 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( templ.Name ));
            
            #line default
            #line hidden
            
            #line 21 ""
            this.Write("\":\n                    return typeof(global::");
            
            #line default
            #line hidden
            
            #line 22 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( templ.GeneratedClass ));
            
            #line default
            #line hidden
            
            #line 22 ""
            this.Write(");\n");
            
            #line default
            #line hidden
            
            #line 23 ""
 } 
            
            #line default
            #line hidden
            
            #line 24 ""
            this.Write("            }\n\n            return null;\n        }\n    }\n}\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public override void Initialize() {
            base.Initialize();
        }
    }
}
